### ISSUE TITLE
Support for multiple speakers

### ISSUE THREAD

**Issue by mojadem** [thewh1teagle/piper-rs#2]
Hello! Does the library currently support selecting a speaker from models with multiple (e.g. [this model](https://huggingface.co/rhasspy/piper-voices/blob/main/en/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx.json)). It appears that it does not, since the only implementation of `get_speakers()` I can find is this:

```rust
fn get_speakers(&self) -> SonataResult<Option<&HashMap<i64, String>>> {
    Ok(None)
}
```

If not, I could take a crack at implementing that in a PR.

**Comment by thewh1teagle** [comment]
Hi
Currently, piper-rs doesn’t support specifying the speaker, but I’d love to add this feature. Contributions are always welcome!

Here’s a quick overview of how I’d approach implementing this:

Locate the `let sid =` line and modify it to retrieve the value from a field in the struct.
Allow users to specify the speaker ID as an optional parameter, perhaps by adding a `set_speaker_id(id: usize)` method.
Implement the `get_speakers` method. At the moment, it doesn’t do anything, but you can read the optional speaker map from the config.
Add an `examples/multi.rs` file. Include instructions in a multi-line comment (like the other examples), and make it possible to pass an optional `sid` via `std::args`.
Let me know if you need any help
